package com.audiohardcore.app;
import android.Manifest;import android.app.Activity;import android.content.ContentUris;import android.content.pm.PackageManager;import android.database.Cursor;import android.media.AudioAttributes;import android.media.MediaPlayer;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.text.Editable;import android.text.TextWatcher;import android.widget.ArrayAdapter;import android.widget.EditText;import android.widget.ListView;import android.widget.TextView;import java.io.IOException;import java.util.ArrayList;import java.util.List;
public class MainActivity extends Activity{
 private final List<String> titles=new ArrayList<>();private final List<Uri> uris=new ArrayList<>();private ArrayAdapter<String> adapter;private MediaPlayer player;private TextView status,nowPlaying;private static final int REQ=44;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);nowPlaying=findViewById(R.id.nowPlaying);ListView list=findViewById(R.id.trackList);EditText search=findViewById(R.id.searchBox);adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,titles);list.setAdapter(adapter);list.setOnItemClickListener((p,v,pos,id)->play(uris.get(pos),titles.get(pos)));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){filter(s.toString());}public void afterTextChanged(Editable e){}});requestAndLoad();}
 private void requestAndLoad(){String perm=android.os.Build.VERSION.SDK_INT>=33?Manifest.permission.READ_MEDIA_AUDIO:Manifest.permission.READ_EXTERNAL_STORAGE;if(checkSelfPermission(perm)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{perm},REQ);else loadMusic();}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)loadMusic();else status.setText("Audio permission is required to scan your local library.");}
 private void loadMusic(){status.setText("Scanning local music…");titles.clear();uris.clear();String[] proj={MediaStore.Audio.Media._ID,MediaStore.Audio.Media.TITLE,MediaStore.Audio.Media.ARTIST,MediaStore.Audio.Media.IS_MUSIC};String sel=MediaStore.Audio.Media.IS_MUSIC+"!=0";try(Cursor c=getContentResolver().query(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,proj,sel,null,MediaStore.Audio.Media.TITLE+" COLLATE NOCASE")){if(c!=null)while(c.moveToNext()){long id=c.getLong(0);String title=c.getString(1);String artist=c.getString(2);titles.add((artist==null?"Unknown Artist":artist)+" — "+(title==null?"Unknown Track":title));uris.add(ContentUris.withAppendedId(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,id));}}adapter.notifyDataSetChanged();status.setText(titles.size()+" tracks available on this device");}
 private void filter(String q){if(q==null)q="";q=q.toLowerCase();ArrayList<String> ft=new ArrayList<>();ArrayList<Uri> fu=new ArrayList<>();for(int i=0;i<titles.size();i++)if(titles.get(i).toLowerCase().contains(q)){ft.add(titles.get(i));fu.add(uris.get(i));}titles.clear();titles.addAll(ft);uris.clear();uris.addAll(fu);adapter.notifyDataSetChanged();}
 private void play(Uri uri,String label){if(player!=null){player.release();player=null;}try{player=new MediaPlayer();player.setAudioAttributes(new AudioAttributes.Builder().setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).setUsage(AudioAttributes.USAGE_MEDIA).build());player.setDataSource(this,uri);player.prepare();player.start();nowPlaying.setText("▶ "+label);}catch(IOException e){nowPlaying.setText("Unable to play: "+label);}}
 @Override protected void onDestroy(){if(player!=null)player.release();super.onDestroy();}
}
